"use client";

import { useEffect, useMemo, useRef, useState, type ComponentType } from "react";
import type { UIMessage } from "ai";
import {
  BarChart3, BookOpenText, Bot, CalendarDays, Check, CheckCircle2, ChevronRight,
  ClipboardList, Clock3, FileText, Info, LayoutDashboard, Menu, MessageSquare,
  Pencil, Plus, Save, Search, Send, Settings, ShieldCheck, Target, Trash2, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Conversation, ConversationContent, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
import { createResearchResult, workplaceReply, type ResearchResult } from "@/lib/local-assistant";

type View = "dashboard" | "research" | "planner" | "chat" | "settings";
type Task = { id: string; title: string; deadline: string; priority: "High" | "Medium" | "Low"; done: boolean };
type ScheduleItem = Task & { time: string; duration: string };
type Activity = { label: string; detail: string };

const STORAGE = "workmate-ai-state-v1";
const initialTasks: Task[] = [
  { id: "t1", title: "Finalize Q3 launch brief", deadline: "2026-09-23", priority: "High", done: false },
  { id: "t2", title: "Review onboarding flow copy", deadline: "2026-09-24", priority: "Medium", done: false },
  { id: "t3", title: "Prepare notes for stakeholder sync", deadline: "2026-09-25", priority: "Medium", done: false },
  { id: "t4", title: "Send research digest to team", deadline: "2026-09-23", priority: "Low", done: true },
];
const starterMessages: UIMessage[] = [{ id: "welcome", role: "assistant", parts: [{ type: "text", text: "Hello — I can help you prepare for a meeting, structure feedback, prioritize competing work, or draft a clear workplace message." }] }];

const nav: { id: View; label: string; icon: ComponentType<{ className?: string }> }[] = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "research", label: "Research Assistant", icon: BookOpenText },
  { id: "planner", label: "Task Planner", icon: ClipboardList },
  { id: "chat", label: "AI Chat", icon: MessageSquare },
  { id: "settings", label: "Settings", icon: Settings },
];

const quickPrompts = [
  "Help me prioritize an urgent request against planned work",
  "Draft a tactful message to move a deadline",
  "How should I structure a difficult feedback conversation?",
];

function Logo() {
  return <div className="grid size-9 shrink-0 place-items-center rounded-lg bg-blush-deep font-display text-sm font-bold text-primary-foreground">W</div>;
}

function Sidebar({ active, select }: { active: View; select: (view: View) => void }) {
  return (
    <div className="flex h-full flex-col gap-1">
      <div className="mb-7 flex items-center gap-2.5 px-2"><Logo /><div><p className="font-display text-base font-semibold">Workmate AI</p><p className="text-[11px] text-muted-foreground">Productivity assistant</p></div></div>
      <p className="px-3 pb-2 text-[11px] font-semibold uppercase text-muted-foreground">Workspace</p>
      {nav.map((item) => {
        const Icon = item.icon;
        return <Button key={item.id} variant="ghost" onClick={() => select(item.id)} className={`h-10 w-full justify-start gap-3 px-3 ${active === item.id ? "bg-blush font-semibold hover:bg-blush" : "text-muted-foreground"}`}><Icon className="size-4" />{item.label}</Button>;
      })}
      <div className="mt-auto rounded-lg border border-line bg-card p-3">
        <div className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="size-4 text-blush-deep" />Private workspace</div>
        <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">Your work is saved only in this browser.</p>
      </div>
    </div>
  );
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0"><p className="text-sm font-medium text-muted-foreground">{eyebrow}</p><h1 className="mt-1 font-display text-3xl font-bold leading-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</div>;
}

function ResponsibleNotice() {
  return <div className="mt-6 flex items-start gap-3 rounded-lg border border-blush-deep/20 bg-blush/40 p-4"><span className="mt-0.5 grid size-6 shrink-0 place-items-center rounded-md bg-blush-deep text-primary-foreground"><Info className="size-3.5" /></span><p className="text-sm leading-relaxed text-foreground/75"><strong>Responsible AI:</strong> AI outputs can be incomplete or inaccurate. Review and verify them before using them for important workplace decisions.</p></div>;
}

function Dashboard({ tasks, activity, go }: { tasks: Task[]; activity: Activity[]; go: (view: View) => void }) {
  const open = tasks.filter((task) => !task.done);
  return <div className="soft-in">
    <PageHeading eyebrow="Your workplace, organized" title="Good morning" description={`You have ${open.length} open tasks and a clear place to move every piece of work forward.`} action={<Button onClick={() => go("chat")}><Bot />Ask Workmate</Button>} />
    <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
      {[{ view: "research" as View, icon: FileText, label: "Summarize", text: "Digest a document" }, { view: "planner" as View, icon: CalendarDays, label: "Schedule", text: "Plan your week" }, { view: "chat" as View, icon: MessageSquare, label: "Draft", text: "Write a clear reply" }, { view: "chat" as View, icon: Target, label: "Decide", text: "Work through trade-offs" }].map((item) => <Button key={item.label} variant="outline" onClick={() => go(item.view)} className="h-auto min-w-0 justify-start rounded-lg border-0 bg-card p-4 text-left shadow-sm hover:bg-blush/50"><item.icon className="size-5 shrink-0 text-blush-deep" /><span className="min-w-0"><span className="block text-xs font-semibold uppercase text-blush-deep">{item.label}</span><span className="mt-1 block truncate text-sm font-medium text-foreground/70">{item.text}</span></span></Button>)}
    </div>
    <div className="mt-6 grid gap-4 xl:grid-cols-3">
      <section className="rounded-lg border border-line bg-card p-5 xl:col-span-2"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Priority tasks</h2><Button variant="ghost" size="sm" onClick={() => go("planner")}>View planner<ChevronRight /></Button></div><div className="mt-4 space-y-2">{tasks.map((task) => <div key={task.id} className="flex items-center gap-3 rounded-md bg-mist px-3 py-3"><span className={`grid size-5 shrink-0 place-items-center rounded border ${task.done ? "border-blush-deep bg-blush-deep text-primary-foreground" : "border-blush-deep"}`}>{task.done && <Check className="size-3" />}</span><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${task.done ? "text-muted-foreground line-through" : ""}`}>{task.title}</p><p className="text-xs text-muted-foreground">Due {task.deadline}</p></div><span className="shrink-0 rounded-md bg-blush px-2 py-1 text-xs font-medium">{task.priority}</span></div>)}</div></section>
      <section className="rounded-lg border border-line bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Research</h2><Button variant="ghost" size="sm" onClick={() => go("research")}>Open<ChevronRight /></Button></div><div className="mt-4 space-y-3"><div className="rounded-md bg-mist p-3"><p className="text-sm font-medium">Your next brief</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Paste an article or describe a topic to extract decisions, insights, and practical recommendations.</p></div><div className="rounded-md bg-mist p-3"><p className="text-sm font-medium">Editable by design</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Refine every generated section before you share or act on it.</p></div></div></section>
      <section className="rounded-lg border border-line bg-card p-5"><h2 className="font-display text-lg font-semibold">Recent AI activity</h2><div className="mt-4 space-y-4">{activity.slice(0, 4).map((item, i) => <div key={`${item.label}-${i}`} className="flex gap-3"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-blush-deep" /><div><p className="text-sm font-medium">{item.label}</p><p className="text-xs text-muted-foreground">{item.detail}</p></div></div>)}</div></section>
      <section className="rounded-lg border border-line bg-card p-5 xl:col-span-2"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Today at a glance</h2><span className="rounded-full bg-blush px-2.5 py-1 text-xs font-semibold">Local workspace</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3">{[{ icon: CheckCircle2, value: tasks.filter(t => t.done).length, label: "Completed" }, { icon: Clock3, value: open.length, label: "Still open" }, { icon: BarChart3, value: activity.length, label: "AI actions" }].map((stat) => <div key={stat.label} className="rounded-md bg-mist p-4"><stat.icon className="size-5 text-blush-deep" /><p className="mt-3 font-display text-3xl font-bold">{stat.value}</p><p className="text-sm text-muted-foreground">{stat.label}</p></div>)}</div></section>
    </div><ResponsibleNotice />
  </div>;
}

function ResearchAssistant({ saved, onSave, onActivity }: { saved: ResearchResult | null; onSave: (r: ResearchResult) => void; onActivity: (a: Activity) => void }) {
  const [topic, setTopic] = useState(""); const [source, setSource] = useState(""); const [result, setResult] = useState<ResearchResult | null>(saved); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const generate = () => { if (!topic.trim() && !source.trim()) { setError("Enter a topic or paste source text first."); return; } setError(""); setLoading(true); window.setTimeout(() => { const next = createResearchResult(topic, source); setResult(next); onSave(next); onActivity({ label: "Created a research brief", detail: topic.trim() || "Pasted article" }); setLoading(false); }, 850); };
  const updateList = (key: "insights" | "points" | "recommendations", index: number, value: string) => { if (!result) return; const next = { ...result, [key]: result[key].map((item, i) => i === index ? value : item) }; setResult(next); onSave(next); };
  return <div className="soft-in"><PageHeading eyebrow="AI Research Assistant" title="Turn reading into action" description="Add a topic or source text. Workmate identifies the core message, useful evidence, and practical next steps." />
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,0.85fr)_minmax(0,1.15fr)]"><section className="rounded-lg border border-line bg-card p-5"><label className="text-sm font-semibold" htmlFor="research-topic">Topic or question</label><Input id="research-topic" maxLength={160} value={topic} onChange={e => setTopic(e.target.value)} className="mt-2" placeholder="e.g. How hybrid work affects team decision speed" /><label className="mt-5 block text-sm font-semibold" htmlFor="research-source">Article or source text</label><Textarea id="research-source" maxLength={12000} value={source} onChange={e => setSource(e.target.value)} className="mt-2 min-h-64 resize-y bg-mist" placeholder="Paste notes, a report excerpt, or an article here…" /><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>{error || "Your source stays in this browser."}</span><span>{source.length}/12,000</span></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={generate} disabled={loading}>{loading ? <><span className="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />Analyzing</> : <><Search />Generate brief</>}</Button><Button variant="outline" onClick={() => { setTopic("AI adoption policies for small teams"); setSource("Small teams are adopting AI tools to reduce repetitive work, but many lack review policies. Managers report faster drafting and analysis, while employees remain concerned about accuracy, privacy, and unclear accountability. Teams with documented review steps and named owners see fewer errors and stronger adoption."); }}>Use example</Button></div></section>
      <section className="min-h-[32rem] rounded-lg border border-line bg-card p-5">{loading ? <div className="grid h-full place-items-center"><div className="text-center"><Shimmer className="font-display text-lg">Analyzing evidence and implications…</Shimmer><p className="mt-2 text-sm text-muted-foreground">Finding the clearest, most actionable signals</p></div></div> : result ? <div className="space-y-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase text-blush-deep">Generated brief</p><h2 className="font-display text-xl font-semibold">Review and edit</h2></div><span className="flex items-center gap-1 text-xs text-muted-foreground"><Pencil className="size-3" />Editable</span></div><div><label className="text-sm font-semibold" htmlFor="summary">Summary</label><Textarea id="summary" value={result.summary} onChange={e => { const next = { ...result, summary: e.target.value }; setResult(next); onSave(next); }} className="mt-2 min-h-28 bg-mist" /></div>{(["insights", "points", "recommendations"] as const).map((key) => <div key={key}><h3 className="text-sm font-semibold capitalize">{key === "points" ? "Important points" : key}</h3><div className="mt-2 space-y-2">{result[key].map((item, index) => <div key={index} className="grid grid-cols-[auto_minmax(0,1fr)] gap-2"><span className="mt-2 grid size-5 place-items-center rounded bg-blush text-xs font-bold">{index + 1}</span><Textarea value={item} onChange={e => updateList(key, index, e.target.value)} className="min-h-16 bg-mist" /></div>)}</div></div>)}</div> : <div className="grid h-full place-items-center px-6 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-lg bg-blush"><BookOpenText className="size-6 text-blush-deep" /></div><h2 className="mt-4 font-display text-xl font-semibold">Your research brief appears here</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">You’ll get a summary, key insights, important points, and practical recommendations — all editable.</p></div></div>}</section></div><ResponsibleNotice /></div>;
}

function TaskPlanner({ tasks, setTasks, schedule, setSchedule, onActivity }: { tasks: Task[]; setTasks: (t: Task[]) => void; schedule: ScheduleItem[]; setSchedule: (s: ScheduleItem[]) => void; onActivity: (a: Activity) => void }) {
  const [title, setTitle] = useState(""); const [deadline, setDeadline] = useState("2026-09-24"); const [priority, setPriority] = useState<Task["priority"]>("Medium"); const [loading, setLoading] = useState(false);
  const add = () => { if (!title.trim()) return; setTasks([...tasks, { id: crypto.randomUUID(), title: title.trim(), deadline, priority, done: false }]); setTitle(""); };
  const plan = () => { if (!tasks.length) return; setLoading(true); window.setTimeout(() => { const order = { High: 0, Medium: 1, Low: 2 }; const active = [...tasks].filter(t => !t.done).sort((a, b) => order[a.priority] - order[b.priority] || a.deadline.localeCompare(b.deadline)); const next = active.map((task, index) => ({ ...task, time: `${String(9 + Math.floor(index * 1.5)).padStart(2, "0")}:${index % 2 ? "30" : "00"}`, duration: task.priority === "High" ? "90 min" : "60 min" })); setSchedule(next); onActivity({ label: "Built a prioritized schedule", detail: `${next.length} work blocks` }); setLoading(false); }, 750); };
  return <div className="soft-in"><PageHeading eyebrow="AI Task Planner" title="Make the workload realistic" description="Capture deadlines and priorities, then create an editable sequence that protects focused work and keeps commitments visible." action={<Button onClick={plan} disabled={loading || tasks.length === 0}>{loading ? "Planning…" : "Build schedule"}</Button>} />
    <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]"><section className="rounded-lg border border-line bg-card p-5"><h2 className="font-display text-lg font-semibold">Task list</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><label className="text-sm font-medium" htmlFor="task-title">Task</label><Input id="task-title" maxLength={140} value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Review the client proposal" className="mt-1.5" /></div><div><label className="text-sm font-medium" htmlFor="deadline">Deadline</label><Input id="deadline" type="date" value={deadline} onChange={e => setDeadline(e.target.value)} className="mt-1.5" /></div><div><label className="text-sm font-medium">Priority</label><Select value={priority} onValueChange={value => setPriority(value as Task["priority"])}><SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="High">High</SelectItem><SelectItem value="Medium">Medium</SelectItem><SelectItem value="Low">Low</SelectItem></SelectContent></Select></div></div><Button onClick={add} className="mt-3"><Plus />Add task</Button><div className="mt-5 space-y-2">{tasks.map(task => <div key={task.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-md bg-mist p-3"><Button size="icon-sm" variant="ghost" aria-label={task.done ? "Mark incomplete" : "Mark complete"} onClick={() => setTasks(tasks.map(t => t.id === task.id ? { ...t, done: !t.done } : t))}>{task.done ? <CheckCircle2 className="text-blush-deep" /> : <span className="size-4 rounded border border-blush-deep" />}</Button><div className="min-w-0"><p className={`truncate text-sm font-medium ${task.done ? "text-muted-foreground line-through" : ""}`}>{task.title}</p><p className="text-xs text-muted-foreground">{task.deadline} · {task.priority}</p></div><Button size="icon-sm" variant="ghost" aria-label="Delete task" onClick={() => setTasks(tasks.filter(t => t.id !== task.id))}><Trash2 /></Button></div>)}</div></section>
      <section className="rounded-lg border border-line bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase text-blush-deep">Editable plan</p><h2 className="font-display text-lg font-semibold">Focused workday</h2></div><CalendarDays className="size-5 text-blush-deep" /></div>{loading ? <div className="grid min-h-80 place-items-center"><Shimmer>Balancing priorities and deadlines…</Shimmer></div> : schedule.length ? <div className="mt-5 space-y-3">{schedule.map((item, index) => <div key={item.id} className="grid grid-cols-[5.5rem_minmax(0,1fr)] gap-3 rounded-md border border-line p-3"><div><Input aria-label="Start time" value={item.time} onChange={e => setSchedule(schedule.map((s, i) => i === index ? { ...s, time: e.target.value } : s))} className="h-8 bg-mist text-center text-xs" /><p className="mt-2 text-center text-xs text-muted-foreground">{item.duration}</p></div><div className="min-w-0"><Input aria-label="Scheduled task" value={item.title} onChange={e => setSchedule(schedule.map((s, i) => i === index ? { ...s, title: e.target.value } : s))} className="h-8 font-medium" /><div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><span className="rounded bg-blush px-2 py-1">{item.priority}</span><span>Due {item.deadline}</span></div></div></div>)}</div> : <div className="grid min-h-80 place-items-center text-center"><div><Clock3 className="mx-auto size-8 text-blush-deep" /><h3 className="mt-3 font-display text-lg font-semibold">Ready when your tasks are</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">Build a schedule to prioritize urgent work and assign realistic focus blocks.</p></div></div>}</section></div><ResponsibleNotice /></div>;
}

function Chat({ messages, setMessages, onActivity }: { messages: UIMessage[]; setMessages: (m: UIMessage[]) => void; onActivity: (a: Activity) => void }) {
  const [status, setStatus] = useState<"ready" | "submitted">("ready"); const inputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { inputRef.current?.focus(); }, [status]);
  const submit = ({ text }: { text: string }) => { const safe = text.trim().slice(0, 2500); if (!safe || status !== "ready") return; const user: UIMessage = { id: crypto.randomUUID(), role: "user", parts: [{ type: "text", text: safe }] }; setMessages([...messages, user]); setStatus("submitted"); window.setTimeout(() => { const assistant: UIMessage = { id: crypto.randomUUID(), role: "assistant", parts: [{ type: "text", text: workplaceReply(safe) }] }; setMessages([...messages, user, assistant]); onActivity({ label: "Answered a workplace question", detail: safe.slice(0, 48) }); setStatus("ready"); }, 650); };
  return <div className="soft-in flex min-h-[calc(100vh-7rem)] flex-col"><PageHeading eyebrow="AI Workplace Chat" title="Work through the next step" description="Ask a specific workplace question and get practical guidance shaped around the situation you describe." />
    <div className="mt-5 flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg border border-line bg-card"><div className="flex items-center justify-between border-b border-line px-4 py-3"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-blush"><Bot className="size-5 text-blush-deep" /></div><div><p className="text-sm font-semibold">Workmate</p><p className="text-xs text-muted-foreground">One conversation · saved locally</p></div></div><Button variant="ghost" size="sm" onClick={() => setMessages(starterMessages)}><Trash2 />Clear</Button></div>
      <div className="grid min-h-0 flex-1 lg:grid-cols-[minmax(0,1fr)_17rem]"><div className="flex min-h-[28rem] min-w-0 flex-col"><Conversation className="min-h-0"><ConversationContent className="mx-auto w-full max-w-3xl gap-5 p-5">{messages.map(message => <Message from={message.role} key={message.id}><MessageContent className={message.role === "user" ? "bg-primary text-primary-foreground" : ""}>{message.parts.map((part, index) => part.type === "text" ? <MessageResponse key={index}>{part.text}</MessageResponse> : null)}</MessageContent></Message>)}{status === "submitted" && <Message from="assistant"><MessageContent><Shimmer>Thinking through the practical next step…</Shimmer></MessageContent></Message>}</ConversationContent><ConversationScrollButton /></Conversation><div className="mx-auto w-full max-w-3xl px-4 pb-4"><PromptInput onSubmit={submit} className="rounded-lg bg-background"><PromptInputTextarea ref={inputRef} maxLength={2500} placeholder="Ask about a meeting, deadline, message, or workplace challenge…" className="min-h-20" /><PromptInputFooter className="justify-end"><PromptInputSubmit status={status} disabled={status !== "ready"} /></PromptInputFooter></PromptInput></div></div><aside className="hidden border-l border-line bg-mist/60 p-4 lg:block"><p className="text-xs font-semibold uppercase text-muted-foreground">Example prompts</p><div className="mt-3 space-y-2">{quickPrompts.map(prompt => <Button key={prompt} variant="outline" onClick={() => submit({ text: prompt })} className="h-auto w-full whitespace-normal bg-card px-3 py-3 text-left text-xs leading-relaxed">{prompt}<Send className="ml-auto shrink-0" /></Button>)}</div><div className="mt-5 rounded-md bg-blush/60 p-3"><p className="text-xs font-semibold">For better answers</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">Include the goal, audience, deadline, and any constraint that matters.</p></div></aside></div></div><ResponsibleNotice /></div>;
}

function SettingsView({ onReset }: { onReset: () => void }) {
  return <div className="soft-in"><PageHeading eyebrow="Settings" title="Your local workspace" description="Workmate is designed as a private frontend-only assistant. There are no accounts, shared databases, or external AI requests." /><div className="mt-6 grid gap-4 md:grid-cols-2"><section className="rounded-lg border border-line bg-card p-5"><ShieldCheck className="size-6 text-blush-deep" /><h2 className="mt-4 font-display text-lg font-semibold">Privacy and storage</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Tasks, research drafts, schedules, and chat messages are stored in localStorage in this browser. Clearing browser data removes them.</p></section><section className="rounded-lg border border-line bg-card p-5"><Bot className="size-6 text-blush-deep" /><h2 className="mt-4 font-display text-lg font-semibold">Local response engine</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">This MVP uses context-aware browser logic rather than a hosted AI model, keeping the app fully frontend-only.</p></section><section className="rounded-lg border border-line bg-card p-5 md:col-span-2"><h2 className="font-display text-lg font-semibold">Reset workspace</h2><p className="mt-1 text-sm text-muted-foreground">Remove saved research, tasks, schedules, activity, and chat from this browser.</p><Button variant="destructive" className="mt-4" onClick={onReset}><Trash2 />Clear local data</Button></section></div><ResponsibleNotice /></div>;
}

export function ProductivityWorkspace() {
  const [view, setView] = useState<View>("dashboard"); const [tasks, setTasks] = useState<Task[]>(initialTasks); const [schedule, setSchedule] = useState<ScheduleItem[]>([]); const [research, setResearch] = useState<ResearchResult | null>(null); const [messages, setMessages] = useState<UIMessage[]>(starterMessages); const [activity, setActivity] = useState<Activity[]>([{ label: "Workspace ready", detail: "All data stays in this browser" }]); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { try { const raw = localStorage.getItem(STORAGE); if (raw) { const saved = JSON.parse(raw) as { tasks?: Task[]; schedule?: ScheduleItem[]; research?: ResearchResult; messages?: UIMessage[]; activity?: Activity[] }; if (saved.tasks) setTasks(saved.tasks); if (saved.schedule) setSchedule(saved.schedule); if (saved.research) setResearch(saved.research); if (saved.messages) setMessages(saved.messages); if (saved.activity) setActivity(saved.activity); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(STORAGE, JSON.stringify({ tasks, schedule, research, messages, activity })); }, [hydrated, tasks, schedule, research, messages, activity]);
  const addActivity = (item: Activity) => setActivity(current => [item, ...current].slice(0, 8));
  const title = useMemo(() => nav.find(item => item.id === view)?.label ?? "Dashboard", [view]);
  const reset = () => { localStorage.removeItem(STORAGE); setTasks(initialTasks); setSchedule([]); setResearch(null); setMessages(starterMessages); setActivity([{ label: "Workspace reset", detail: "Local data cleared" }]); setView("dashboard"); };
  return <div className="min-h-screen bg-mist text-ink"><header className="sticky top-0 z-30 border-b border-line bg-card/95"><div className="mx-auto grid h-16 max-w-[1440px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 px-4 sm:px-6"><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open navigation"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-72 p-4"><SheetTitle className="sr-only">Navigation</SheetTitle><Sidebar active={view} select={setView} /></SheetContent></Sheet><div className="flex min-w-0 items-center gap-2.5 lg:hidden"><Logo /><span className="truncate font-display text-base font-semibold">Workmate AI</span></div><p className="hidden truncate text-sm text-muted-foreground lg:block">{title}</p><div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full bg-mist px-3 py-1.5 text-xs text-muted-foreground sm:flex"><span className="size-1.5 rounded-full bg-blush-deep" />Saved locally</span><div className="grid size-9 place-items-center rounded-full bg-blush text-sm font-medium">YU</div></div></div></header><div className="mx-auto flex max-w-[1440px]"><aside className="sticky top-16 hidden h-[calc(100vh-4rem)] w-60 shrink-0 border-r border-line p-4 lg:block"><Sidebar active={view} select={setView} /></aside><main className="min-w-0 flex-1 px-4 py-6 sm:px-6 lg:px-8">{view === "dashboard" && <Dashboard tasks={tasks} activity={activity} go={setView} />}{view === "research" && <ResearchAssistant saved={research} onSave={setResearch} onActivity={addActivity} />}{view === "planner" && <TaskPlanner tasks={tasks} setTasks={setTasks} schedule={schedule} setSchedule={setSchedule} onActivity={addActivity} />}{view === "chat" && <Chat messages={messages} setMessages={setMessages} onActivity={addActivity} />}{view === "settings" && <SettingsView onReset={reset} />}</main></div></div>;
}